# Generated by Django 2.2.1 on 2021-05-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price_usd',
            new_name='_price_eur',
        ),
    ]
