# Generated by Django 2.2.1 on 2021-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191002_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Забанен',
                'verbose_name_plural': 'Забанены',
            },
        ),
    ]
