# Generated by Django 2.2.1 on 2021-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_blacklistemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistemail',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
