# Generated by Django 2.2.1 on 2019-12-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_dict', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_name', models.CharField(blank=True, max_length=255)),
                ('max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('final_url', models.CharField(blank=True, max_length=500)),
                ('inner_labels', models.CharField(default='generic', max_length=20)),
                ('chk', models.BooleanField(default=False)),
                ('dont_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_rus', models.CharField(blank=True, max_length=100, null=True)),
                ('car_eng', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Negative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative', models.CharField(max_length=255, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.AdGroups')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('labels', models.CharField(blank=True, max_length=255)),
                ('criterion_type', models.CharField(blank=True, max_length=20, null=True)),
                ('max_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.AdGroups')),
            ],
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fast_link_yand', models.CharField(blank=True, max_length=66, null=True)),
                ('fast_link_yand_desc', models.CharField(blank=True, max_length=126, null=True)),
                ('fast_link_yand_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.Cars')),
            ],
        ),
        migrations.AddField(
            model_name='adgroups',
            name='camp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.Campaigns'),
        ),
        migrations.AddField(
            model_name='adgroups',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group_dict.Groups'),
        ),
        migrations.CreateModel(
            name='AddsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline1', models.CharField(blank=True, max_length=30)),
                ('headline2', models.CharField(blank=True, max_length=30)),
                ('headline3', models.CharField(blank=True, max_length=30)),
                ('description1', models.CharField(blank=True, max_length=90)),
                ('description2', models.CharField(blank=True, max_length=90)),
                ('description3', models.CharField(blank=True, max_length=90)),
                ('path1', models.CharField(blank=True, max_length=15)),
                ('path2', models.CharField(blank=True, max_length=15)),
                ('variant', models.CharField(choices=[('one', 1), ('second', 2), ('third', 3)], default='one', max_length=20)),
                ('camaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ads_work.Campaigns')),
            ],
        ),
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline1', models.CharField(blank=True, max_length=30)),
                ('path1', models.CharField(blank=True, max_length=15)),
                ('path2', models.CharField(blank=True, max_length=15)),
                ('headline2', models.CharField(blank=True, max_length=30)),
                ('headline3', models.CharField(blank=True, max_length=30)),
                ('description1', models.CharField(blank=True, max_length=90)),
                ('description2', models.CharField(blank=True, max_length=90)),
                ('description3', models.CharField(blank=True, max_length=90)),
                ('variant', models.CharField(choices=[('one', 1), ('second', 2), ('third', 3)], default='one', max_length=20)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ads_work.AdGroups')),
                ('camp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ads_work.Campaigns')),
            ],
        ),
    ]
